"""Create a small, licensed-by-construction arcade video and exact annotations.

This is a deterministic integration fixture. It tests the pipeline without
claiming that ground-truth labels were generated by an AI labeling provider.
"""

from __future__ import annotations

import json
import math
import random
from pathlib import Path

import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont


HERE = Path(__file__).resolve().parent
WIDTH, HEIGHT, FPS, COUNT = 640, 360, 4, 32


def typeface(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    windows = Path("C:/Windows/Fonts/seguisb.ttf" if bold else "C:/Windows/Fonts/segoeui.ttf")
    try:
        return ImageFont.truetype(str(windows if windows.exists() else "DejaVuSans.ttf"), size)
    except OSError:
        return ImageFont.load_default()


def circle_object(draw: ImageDraw.ImageDraw, x: int, y: int, radius: int, color: str) -> list[int]:
    draw.ellipse((x-radius, y-radius, x+radius, y+radius), fill=color, outline="#FFF4CF", width=3)
    draw.ellipse((x-radius//2, y-radius//2, x-radius//6, y-radius//5), fill="#FFFFFF")
    draw.polygon([(x, y-radius+2), (x+8, y-radius-12), (x+18, y-radius-8), (x+8, y-radius+1)], fill="#8EEE85")
    return [x-radius, y-radius-12, x+radius, y+radius]


def bomb_object(draw: ImageDraw.ImageDraw, x: int, y: int, radius: int) -> list[int]:
    draw.ellipse((x-radius, y-radius, x+radius, y+radius), fill="#272939", outline="#D1D9E4", width=3)
    draw.arc((x-radius//2, y-radius//2, x+radius//2, y+radius//2), 210, 330, fill="#66718B", width=6)
    draw.line((x, y-radius, x+7, y-radius-12, x+14, y-radius-14), fill="#E2C58D", width=4)
    draw.ellipse((x+11, y-radius-19, x+18, y-radius-12), fill="#FFAF59")
    return [x-radius, y-radius-19, x+radius, y+radius]


def frame(index: int) -> tuple[Image.Image, list[dict]]:
    rng = random.Random(7100 + index)
    image = Image.new("RGB", (WIDTH, HEIGHT), "#111924")
    draw = ImageDraw.Draw(image)
    for y in range(HEIGHT):
        shade = int(21 + 17 * y / HEIGHT)
        draw.line((0, y, WIDTH, y), fill=(12, shade, 35 + shade//3))
    for gx in range(0, WIDTH, 40):
        draw.line((gx, 0, gx, HEIGHT), fill="#25333D", width=1)
    for gy in range(0, HEIGHT, 40):
        draw.line((0, gy, WIDTH, gy), fill="#25333D", width=1)
    for _ in range(13):
        sx, sy = rng.randrange(WIDTH), rng.randrange(HEIGHT)
        draw.ellipse((sx, sy, sx+2, sy+2), fill="#5A7793")
    draw.rounded_rectangle((18, 16, 622, 62), radius=13, fill="#0B1119", outline="#405C68", width=2)
    draw.text((32, 26), "FRUIT CATCH", font=typeface(25, True), fill="#F3F7E8")
    draw.text((430, 32), f"ROUND 01   /   {index+1:02d}", font=typeface(14, True), fill="#C3D3D9")
    draw.rounded_rectangle((20, 306, 620, 341), radius=9, fill="#0B1119", outline="#3E5965")
    draw.text((36, 315), "CATCH THE FRUIT. AVOID THE BOMBS.", font=typeface(15, True), fill="#C9ED95")
    draw.text((526, 315), "2400", font=typeface(16, True), fill="#F9C171")

    # Distinct positions in every frame keep the held-out frames meaningful.
    x1 = 104 + (index * 37) % 430
    y1 = 124 + int(27 * math.sin(index * 0.61))
    x2 = 156 + (index * 51 + 127) % 365
    y2 = 225 + int(22 * math.cos(index * 0.47))
    xb = 112 + (index * 43 + 217) % 418
    yb = 168 + int(37 * math.sin(index * 0.39 + 1.0))
    # Shift overlapping objects, preserving a clear instance for training.
    if abs(xb-x1) < 85 and abs(yb-y1) < 70:
        xb = max(70, min(570, xb + 115))
    boxes = [
        {"class": "fruit", "xyxy": circle_object(draw, x1, y1, 26 + index % 4, "#F56A52")},
        {"class": "fruit", "xyxy": circle_object(draw, x2, y2, 25 + (index//3) % 4, "#FFD05A")},
        {"class": "bomb", "xyxy": bomb_object(draw, xb, yb, 24 + (index//2) % 3)},
    ]
    return image, boxes


def main() -> None:
    HERE.mkdir(parents=True, exist_ok=True)
    video = cv2.VideoWriter(str(HERE / "input.mp4"), cv2.VideoWriter_fourcc(*"mp4v"), FPS, (WIDTH, HEIGHT))
    if not video.isOpened():
        raise RuntimeError("OpenCV could not create the fixture video")
    manifest = []
    for index in range(COUNT):
        image, boxes = frame(index)
        manifest.append({"frame": index + 1, "objects": boxes})
        video.write(cv2.cvtColor(np.asarray(image), cv2.COLOR_RGB2BGR))
    video.release()
    (HERE / "ground_truth.json").write_text(json.dumps({"fps": FPS, "size": [WIDTH, HEIGHT], "frames": manifest}, indent=2), encoding="utf-8")
    print(f"Created {COUNT} original gameplay frames and exact ground truth: {HERE / 'input.mp4'}")


if __name__ == "__main__":
    main()
